# Generated by Django 3.2.20 on 2023-07-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packinglist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed']},
        ),
    ]
