# Generated by Django 4.2.3 on 2023-07-28 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packinglist', '0003_alter_packinglist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='packing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='packinglist.packinglist'),
        ),
    ]
