# Generated by Django 4.2.3 on 2023-07-30 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packinglist', '0004_alter_task_packing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_task_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
